import { motion } from "framer-motion";
import { Navbar } from "@/components/landing/Navbar";
import { Footer } from "@/components/landing/Footer";
import { Sparkles } from "lucide-react";

export default function Terms() {
    return (
        <div className="min-h-screen bg-background">
            <Navbar />
            <main className="container mx-auto px-4 py-32 max-w-3xl">
                <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
                    <div className="flex items-center gap-3 mb-8">
                        <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-primary to-accent-foreground flex items-center justify-center">
                            <Sparkles className="w-5 h-5 text-primary-foreground" />
                        </div>
                        <h1 className="text-3xl font-display font-bold">Terms of Service</h1>
                    </div>
                    <p className="text-muted-foreground mb-8">Last updated: February 2026</p>

                    <div className="prose prose-invert max-w-none space-y-8">
                        <section>
                            <h2 className="text-xl font-semibold mb-3">1. Acceptance of Terms</h2>
                            <p className="text-muted-foreground leading-relaxed">
                                By accessing and using Ascend Career, you accept and agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our service.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-xl font-semibold mb-3">2. Use of Service</h2>
                            <p className="text-muted-foreground leading-relaxed">
                                Ascend Career is an AI-powered career guidance platform. You may use our service for your personal, non-commercial career development purposes. You agree not to misuse the service, attempt to circumvent rate limits, or use it in any way that violates applicable laws.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-xl font-semibold mb-3">3. User Accounts</h2>
                            <p className="text-muted-foreground leading-relaxed">
                                You are responsible for maintaining the confidentiality of your account credentials. You agree to notify us immediately of any unauthorized use of your account. We reserve the right to terminate accounts that violate these terms.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-xl font-semibold mb-3">4. AI-Generated Content</h2>
                            <p className="text-muted-foreground leading-relaxed">
                                Career advice and recommendations generated by our AI are for informational purposes only and should not be considered professional career counseling. Always use your own judgment when making career decisions. We are not liable for outcomes resulting from AI-generated advice.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-xl font-semibold mb-3">5. Limitation of Liability</h2>
                            <p className="text-muted-foreground leading-relaxed">
                                Ascend Career is provided "as is" without warranties of any kind. We shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of our service.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-xl font-semibold mb-3">6. Changes to Terms</h2>
                            <p className="text-muted-foreground leading-relaxed">
                                We reserve the right to modify these terms at any time. Continued use of Ascend Career after changes constitutes acceptance of the new terms. We will notify users of significant changes via email.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-xl font-semibold mb-3">7. Contact</h2>
                            <p className="text-muted-foreground leading-relaxed">
                                For questions about these Terms, contact us at{" "}
                                <a href="mailto:legal@ascendcareer.ai" className="text-primary hover:underline">
                                    legal@ascendcareer.ai
                                </a>
                            </p>
                        </section>
                    </div>
                </motion.div>
            </main>
            <Footer />
        </div>
    );
}
